spring:
  profiles:
    active: dev
---
spring:
  profiles: production
  data:
    mongodb:
      database: carminp
      uri: <%= ENV['MONGOLAB_URI'] %>
---
spring:
  profiles: dev
  data:
    mongodb:
      database: carminp
