spring:
  social:
    facebook:
      app-secret: 4ec7bad30457d1e57db8fe556c8b0595
      app-id: 1017666058284084
  profiles:
    active: dev
---
spring:
  profiles: production
  data:
    mongodb:
      database: carminp
logging:
  file: prod-log.log
server:
  port: 8080
---
spring:
  profiles: dev
  data:
    mongodb:
      database: carminp
server:
  context-path: /carminp-api
logging:
  file: dev-log.log
