spring:
  profiles:
    active: dev
---
spring:
  profiles: production
  data:
    mongodb:
      database: carminp
      uri: mongodb://carminp:carminp1@ds059694.mongolab.com:59694/heroku_tjp72kxk
---
spring:
  profiles: dev
  data:
    mongodb:
      database: carminp
