---
- name: Add apt-key
  apt_key:
    id="7F0CEB10"
    state=present
    keyserver=hkp://keyserver.ubuntu.com:80

- name: Add mongodb repo
  apt_repository:
    repo: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
    state: present

- name: Install MongoDB
  apt:
    pkg: "mongodb-org"
    state: present

- name: Creates directory for data
  file: path=/data/db state=directory owner=vagrant group=vagrant mode=0775

- name: Ensure MongoDB is running
  service:
    name: mongod
    state: started

- name: Install pymongo if users are to be added.
  apt: >
    pkg={{ item }}
  with_items:
   - python-pymongo
  when: mongodb_users|length > 0