---
- name: Add MongoDB users
  mongodb_user: >
    database="{{ item.database }}"
    name="{{ item.username }}"
    password="{{ item.password }}"
    roles="{{ item.roles | default('readWrite,dbAdmin,userAdmin') }}"
    state="present"
  with_items: mongodb_users
  notify: restart mongodb
  when: mongodb_users|length > 0